### ISSUE TITLE
strange error while testing ticket 21479

### ISSUE THREAD

**Issue by videlec** [sagemath/sage-patchbot#101]
In the log of ticket 21479 on librae I got

```
Cloning into '/home/vincent/tmp/tmpFzCWUK-sage-git-temp-21479'...
done.
git branch -f patchbot/base remotes/origin/patchbot/base
Branch patchbot/base set up to track remote branch patchbot/base from origin.
git branch -f patchbot/ticket_upstream remotes/origin/patchbot/ticket_upstream
Branch patchbot/ticket_upstream set up to track remote branch patchbot/ticket_upstream from origin.
Apply -- 8 seconds
fatal: Unable to read current working directory: No such file or directory
Traceback (most recent call last):
  File "/nfs4/home6/vdelecro/.local/lib/python2.7/site-packages/sage_patchbot/patchbot.py", line 1327, in report_ticket
    tags = [describe_branch('patchbot/base', tag_only=True),
  File "/usr/labri/vdelecro/.local/lib/python2.7/site-packages/sage_patchbot/util.py", line 235, in describe_branch
    universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', 'describe', '--tags', '--match', '[0-9].[0-9]*', 'patchbot/base']' returned non-zero exit status 128
REPORT
{'base': '7.5.beta0',
 'deps': [21501],
 'machine': ['Ubuntu', '14.04', 'x86_64', '3.13.0-100-generic', 'librae'],
 'owner': 'unknown owner',
 'patchbot_version': '2.6.3',
 'pending_status': 'applied',
 'plugins': (),
 'spkgs': [],
 'status': 'Pending',
 'time': '2016-10-23 20:16:49',
 'user': 'vdelecro'}
21479: Pending
ok (report successfully posted)
./configure
sh: 0: getcwd() failed: No such file or directory
sh: 1: ./configure: not found
Apply -- 8 seconds
Traceback (most recent call last):
  File "/nfs4/home6/vdelecro/.local/lib/python2.7/site-packages/sage_patchbot/patchbot.py", line 1053, in test_a_ticket
    do_or_die('./configure')
  File "/usr/labri/vdelecro/.local/lib/python2.7/site-packages/sage_patchbot/util.py", line 179, in do_or_die
    raise exn_class("{} {}".format(res, cmd))
Exception: 32512 ./configure
2016-10-23 20:16:49
8 seconds
```

**Comment by fchapoton** [comment]
this is not a safe ticket. Testing unsafe tickets is currently totally broken
