### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by videlec** [sagemath/sage-patchbot#132]
After testing ticket 0 the patchbot quasar stops suddenly with
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/labri/vdelecro/.local/lib/python3.5/site-packages/sage_patchbot/patchbot.py", line 1627, in <module>
    main(args)
  File "/usr/labri/vdelecro/.local/lib/python3.5/site-packages/sage_patchbot/patchbot.py", line 1586, in main
    res = patchbot.test_a_ticket(0)
  File "/usr/labri/vdelecro/.local/lib/python3.5/site-packages/sage_patchbot/patchbot.py", line 1256, in test_a_ticket
    if maybe_temp_root.endswith(temp_build_suffix + str(ticket['id'])):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
As can be seen from the traceback the computer runs Python 3.5.

**Comment by videlec** [comment]
@embray: it seems to be related to commits around temporary directories like `2b49c27`. Do you know what should be done?

**Comment by embray** [comment]
@videlec

**Comment by embray** [comment]
Try @ 481fc3e

**Comment by videlec** [comment]
Thanks for taking care of it. quasar is now running with sage-patchbot at 481fc3e

**Comment by embray** [comment]
Great, thanks for checking.  I'll make a new release with this fix then.

**Comment by embray** [comment]
Release v2.8.1
