### ISSUE TITLE
Error in python 3.8

### ISSUE THREAD

**Issue by miguelmarco** [sagemath/sage-patchbot#140]
Trying to run a patchbot in arch linux, I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/patchbot/.local/lib/python3.8/site-packages/sage_patchbot/patchbot.py", line 357, in <module>
    class Patchbot(object):
  File "/home/patchbot/.local/lib/python3.8/site-packages/sage_patchbot/patchbot.py", line 405, in Patchbot
    "machine": machine_data(),
  File "/home/patchbot/.local/lib/python3.8/site-packages/sage_patchbot/patchbot.py", line 253, in machine_data
    dist_name, dist_version, dist_id = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

Apparently, the version of the `platform`module in python 3.8m doesn't include the `linux_distribution` function.

**Comment by fchapoton** [comment]
Thanks for your message.
I have fixed that in the latest master branch.
