### ISSUE TITLE
trying to fetch closed ticket should give meaningful error

### ISSUE THREAD

**Issue by rwst** [sagemath/sage-patchbot#40]
At the moment, trying to fetch a closed ticket with `-ticket=12345` gives:

```
Traceback (most recent call last):
  File "/home/ralf/sage/local/bin/patchbot/patchbot.py", line 828, in main
    patchbot.test_a_ticket(ticket)
  File "/home/ralf/sage/local/bin/patchbot/patchbot.py", line 449, in test_a_ticket
    fetch_from_trac(ticket_id)
  File "/home/ralf/git/sage-patchbot/src/trac.py", line 297, in fetch_from_trac
    raise ConfigException, exn.message
ConfigException: 256 git fetch git://trac.sagemath.org/sage.git +4fdef7436a08d4ad2af8900d81816f440d7f9c34:patchbot/ticket_upstream
```

That's because trac will deny the fetch, and `git fetch` just returns `1` without explanation.

**Comment by fchapoton** [comment]
There is now a useful answer:
```

python3 -m sage_patchbot.patchbot --sage-root=/home/chapoton/sage --ticket=12345 --skip-base
...
[2017-02-28 17:08:23] testing given ticket #12345
[2017-02-28 17:08:23] tried to test a closed ticket! shame!
```
