### ISSUE TITLE
patchbot should clean temporary files

### ISSUE THREAD

**Issue by videlec** [sagemath/sage-patchbot#87]
The patchbot (or Sage indirectly) fills /tmp/ with a lot with temporary files. As a consequence, patchbot refuses to test ticket (but do not crash!)

    Traceback (most recent call last):
      File ".../sage_patchbot/patchbot.py", line 997, in test_a_ticket
        safe_only=self.config['safe_only'])
      File ".../sage_patchbot/trac.py", line 322, in pull_from_trac
        ensure_free_space(tmp_dir)
      File ".../sage_patchbot/util.py", line 252, in ensure_free_space
        raise ConfigException(msg.format(N, free, path))
    ConfigException: Refusing to build with less than 4G free (2830778368 bytes available on /tmp/tmpvFZqMQ-sage-git-temp-19213)

**Comment by videlec** [comment]
Indeed... there is a "--cleanup" option. Trying it on librae. Might be wise to actually set it by default.

**Comment by videlec** [comment]
The patchbot on librae does now uses the "--cleanup" option but /tmp/ is still full of mess.
{{{
Rtmp39mo1y   foou1TVf0              timer_createt2nYO_.c  tm7v37jX  tmFJJzsk  tmMFYLfd  tmUxrjMn  tmaTib6b  tmiKWFqA   tmp4CjWRE  tmpoy3Xyc  tmuthK11
Rtmp4TkbSK   foou1TVf0.c            timer_createuQrlSb.c  tm8GIlaM  tmFrXrkg  tmMdLWRc  tmVSCuVD  tmagscPd  tmijl0xI   tmp6XgWHn  tmppJd1I   tmuwFeD5
Rtmp5itVyn   foou1TVf0.i            timer_createwcYIuD.c  tm8lWvAf  tmG3ylub  tmMjlpWc  tmVrGo5w  tmaq9NtI  tmiwGxL9   tmpAuna0H  tmppXepQ   tmvPwBEO
Rtmp7oMBs4   hsperfdata_vdelecro    timer_createzG_400.c  tm8mHxHp  tmGSm8bI  tmMvQwMd  tmVwZqrm  tmb4yGt1  tmjeKdwB   tmpE7mM63  tmppv8lZI  tmw4nKl4
RtmpH1eVRU   lost+found             tm05beCV              tm9Rd2VO  tmGcP2B2  tmMvzHnn  tmW00Q6f  tmb64r6N  tmkTb7OP   tmpFYAGMf  tmpq9cLC4  tmwO26tn
RtmpIWgPTW   sphinx-err-26s7d3.log  tm0cg9t1              tm9VTOgJ  tmGezOyO  tmMzC5HN  tmW1773i  tmbvE9jm  tmkroLy4   tmpJhDNHg  tmptrq56Q  tmwPsxIE
RtmpM1IGYv   sphinx-err-31BxxF.log  tm0d68lJ              tm9r6vXO  tmGmFbGh  tmN03C2n  tmWAcIgi  tmcMmlbm  tmlChR4z   tmpKMK_oM  tmpujltVx  tmx3y0fO
RtmpNibB3M   sphinx-err-BIH6cB.log  tm0oLWe3              tmAIV6Ah  tmHTtEul  tmN4h13F  tmWTFTbl  tmcghWD4  tmlIWwnD   tmpLMG9PL  tmpvDggmz  tmx4k1tP
RtmpRuXJYO   sphinx-err-_kqSc2.log  tm1FAaw1              tmAOQqCb  tmHgbVtk  tmNImkvW  tmWajtg9  tmcsSnbl  tmlTs8xi   tmpLYNT9d  tmpxUnyg3  tmxLLSIE
RtmpeblTkz   sphinx-err-akPVwQ.log  tm1JFbW6              tmARy6Nl  tmHjLBSp  tmNLyz9W  tmWb2gbD  tmdnSerk  tmlWv3nN   tmpLzX_ES  tmpxkAhjE  tmxVVv9o
Rtmpgv0zUr   sphinx-err-evDPJp.log  tm1tUSRJ              tmAZL2Lr  tmIAgqCA  tmO2ONzQ  tmWhLvV2  tmeJCddv  tmlkar7Q   tmpMEtPaA  tmpxzPcQg  tmxw8jKz
RtmpioHjHm   sphinx-err-f25flb.log  tm2r3GKH              tmAg85On  tmIKe4MF  tmOm6g2E  tmWvwbsx  tmeYRGfB  tmlnkYSN   tmpMEvwek  tmpyMYE89  tmyRaHNx
RtmpkBaPoj   sphinx-err-jPnPrm.log  tm2zkMmW              tmAstlmZ  tmIZ3hyl  tmOqDXKd  tmXCKViQ  tmebVjHS  tmlusMZ0   tmpQb3kEA  tmpzhaaGQ  tmyT18XD
Rtmpsg0QT4   sphinx-err-mY9OkM.log  tm3XHlls              tmBKLXif  tmInYydM  tmP5tPgK  tmXLgIG5  tmek53pr  tmm6tWMz   tmpVvP_28  tmqBKhdX   tmyUaRmS
RtmptXM0kW   sphinx-err-tDHjBk.log  tm3fUXvi              tmBSlV4X  tmJH8piA  tmPXpo6a  tmXRpkQS  tmevV6tp  tmmIvG6w   tmpXmHMa   tmqFGaih   tmykv6IB
Rtmpwkw99N   sphinx-err-tRSOar.log  tm46pixt              tmBcp1da  tmJIqKyP  tmQoG4xf  tmXjTNSM  tmf9BuzG  tmn6InTX   tmpXyGyJw  tmrUQNJ9   tmz0KPyy
RtmpylJ0IN   ssh-ZZR5i1AtnM         tm4QmLju              tmBe4I34  tmJPoWX9  tmR7RZgf  tmXoQ56q  tmfAPyI4  tmnir4zV   tmpa3gzw6  tmrgIve0   tmz4QL9b
RtmpytH751   timer_create8hoA5f.c   tm4i7iqG              tmBwxRkD  tmJRhZmZ  tmR8ovEE  tmY7sgO5  tmfyFW4i  tmoKDsQf   tmpaNypDa  tmsBLDgH   tmz6iFZV
fooIdboo4    timer_createCJMhLk.c   tm4vLXif              tmC5v4dX  tmJr24qb  tmRwEVCZ  tmYSaMeu  tmgF7WPe  tmod5jLX   tmpbPrgIU  tmsGHb0F   tmzKnUVc
fooIdboo4.c  timer_createGrTsID.c   tm5BCVvI              tmCJ4Pf7  tmK31MuZ  tmS264Cq  tmYZXroH  tmgHqvpR  tmoiIDul   tmpcRDRDy  tmsmqVBN   tmzhOc66
fooIdboo4.i  timer_createKEWCTm.c   tm5ogbFJ              tmDFl4YX  tmKMqko7  tmSQ27m0  tmYp4tRI  tmh1MfPa  tmonyDwB   tmpeH61L5  tmtDqJzV
foohhH9De    timer_createLZxQw0.c   tm5yN9D7              tmDivaBO  tmL0xO80  tmSV89CY  tmZCsvrb  tmhOXbpq  tmopysJP   tmpgJ3i1   tmtvDEXI
foohhH9De.c  timer_createPUjFy3.c   tm6798kN              tmDlXNdL  tmL4GCSn  tmSVxpko  tmZMJXF9  tmhPS1YH  tmp0UC6H2  tmphrpBgM  tmu6mMPn
foohhH9De.i  timer_createSNnVA8.c   tm6GbUfb              tmEiPjIl  tmLF3J9v  tmSsDsYW  tmZTzpvn  tmheiGSa  tmp0V2kRT  tmpkcOsPh  tmuDRLHr
fooiluY69    timer_createWEODvY.c   tm6NGoMA              tmEukg1u  tmLcgj8E  tmTI3Jqk  tmZi5DE9  tmi5P0cG  tmp0XwBSl  tmpmaQV5V  tmuZv7QW
fooiluY69.c  timer_createhzFvBq.c   tm76WsNO              tmF1ynR0  tmLrTqFG  tmTX3qBt  tmZoWuqG  tmiFnHlE  tmp1XwiuK  tmpn9a4x2  tmuhVRn4
fooiluY69.i  timer_createqS99iN.c   tm7VSWvN              tmF8LKtk  tmLtt7Yr  tmUIpzhq  tmaIlzNs  tmiJMGvP  tmp37FlRM  tmpnFYqL6  tmuqFlXR
}}}

**Comment by fchapoton** [comment]
I am not sure the patchbot is to be blamed here.
The Rtmp*** files probably come from R.

**Comment by videlec** [comment]
This might be **indirectly** the patchbot. But wihtout the patchbot, there is nothing in /tmp/ ;-)

**Comment by fchapoton** [comment]
I have tried to improve the situation in my latest commits. At least one case was needing care, indeed.

**Comment by videlec** [comment]
Good! Thanks.

That being said, there are other left over of the patchbot. Namely, "install.log", "dochtml.log" in SAGE_ROOT/logs. They can become pretty big pretty quickly and this is duplicated information. What do you think about "--cleanup" option being so that it also delete "install.log" and "dochtml.log"?

**Comment by videlec** [comment]
I have still have a lot in `/tmp/`. Both folders of the form `RtmpXXX`  or `tmpXXX as well as files `sphinx-err-0fFgTA.log`.

On the other hand, some files now appear in the Sage repository itself (should be Cython related)

    __nfs4_home6_vdelecro__sage_temp_quasar_14495_dir_eIkmMz_src_pyx.cpp
    __nfs4_home6_vdelecro__sage_temp_quasar_14495_dir_eIkmMz_src_pyx.html
    ...

(I have about a hundred of them)
