### ISSUE TITLE
wished support fir unsafe tickets

### ISSUE THREAD

**Issue by jakobkroeker** [sagemath/sage-patchbot#93]
https://trac.sagemath.org/ticket/17254 is a recent unsafe ticket (upgrade Singular to Singular4)
It would be nice to have again support for unsafe tickets.

I hacked into the patchbot allowing unsafe tickets and got the following:

```
> Successfully unpacked
Sha1 of singular-4.0.3p3.tar.bz2 is dd68e84ef7d0e6c35994e0fce0faa8edf38a7bb1
Traceback (most recent call last):
  File "/home/jakobkroeker/.local/lib/python2.7/site-packages/sage_patchbot/patchbot.py", line 1046, in test_a_ticket
    self.check_spkg(spkg)
  File "/home/jakobkroeker/.local/lib/python2.7/site-packages/sage_patchbot/patchbot.py", line 1227, in check_spkg
    given_sha = open(path).read().splitlines()[1].split('=')[1]
IOError: [Errno 2] No such file or directory: 'build/pkgs/singular/checksums.ini'
http://www.lmona.de/files/sage/singular-4.0.3p3.tar.bz2 -- 26 seconds
Apply -- 7751 seconds
http://www.lmona.de/files/sage/singular-4.0.3p3.tar.bz2 -- 26 seconds
2016-10-04 21:51:04
7777 seconds
[2016-10-04 21:51:06] Reporting #17254 with status Spkg
fatal: Unable to read current working directory: Datei oder Verzeichnis nicht gefunden
Traceback (most recent call last):
  File "/home/jakobkroeker/.local/lib/python2.7/site-packages/sage_patchbot/patchbot.py", line 1328, in report_ticket
    tags = [describe_branch('patchbot/base', tag_only=True),
  File "/home/jakobkroeker/.local/lib/python2.7/site-packages/sage_patchbot/util.py", line 235, in describe_branch
    universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', 'describe', '--tags', '--match', '[0-9].[0-9]*', 'patchbot/base']' returned non-zero exit status 128
[2016-10-04 21:51:06] #17254: Spkg
REPORT
{'base': '7.4.beta6',
 'deps': [17635],
 'machine': ['Ubuntu',
             '12.04',
             'x86_64',
             '3.2.0-70-generic',
             'x200t-ThinkPad-X200-Tablet'],
 'owner': 'unknown owner',
 'patchbot_version': '2.6.3',
 'plugins': [],
 'spkgs': [u'http://www.lmona.de/files/sage/singular-4.0.3p3.tar.bz2'],
 'status': 'Spkg',
 'time': '2016-10-04 21:51:06',
 'user': 'jakobkroeker'}
17254: Spkg
ok (report successfully posted)
[2016-10-04 21:51:15] Done reporting #17254
Traceback (most recent call last):
  File "/home/jakobkroeker/.local/lib/python2.7/site-packages/sage_patchbot/patchbot.py", line 1509, in main
    patchbot.test_a_ticket(ticket)
  File "/home/jakobkroeker/.local/lib/python2.7/site-packages/sage_patchbot/patchbot.py", line 1185, in test_a_ticket
    shutil.rmtree(maybe_temp_root)
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 235, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/tmp8iZiiy-sage-git-temp-17254'
```

**Comment by jakobkroeker** [comment]
probably the issue is caused because my tmp folder was too small

is it possible to support to pass a directory path for unsafe tickets?

It would be too much work form me to increase the size  tmp folder on my computer...
